# Generated by Django 6.0 on 2025-12-11 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_queue_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='phone_number',
            field=models.CharField(default='0000000000', max_length=15),
        ),
        migrations.AddField(
            model_name='token',
            name='user_name',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
    ]
